sudo: required

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.7.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
