sudo: required

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

services:
  - docker

script:
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - docker version
  - docker-compose version
  - sbt ++$TRAVIS_SCALA_VERSION clean dockerCompose/publish-local dockerComposeTemplates/publish-local
  - sbt ++$TRAVIS_SCALA_VERSION clean docker:publish-local
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
  - sbt ++$TRAVIS_SCALA_VERSION updateImpactSubmit
