@import cakesolutions.docker.testkit.DockerComposeTestKit._
@( image: String, dockerfile: DockerFile )
FROM @image

USER root

RUN apt-get update && apt-get install -y libfiu-dev fiu-utils

USER daemon

ENTRYPOINT [ "/usr/bin/fiu-run", "-x", @{ (dockerfile.entrypoint ++ dockerfile.cmd).mkString("\"", "\", \"", "\"") } ]
